[package]
name = "ldk-tutorial-node"
version = "0.1.0"
authors = ["Valentine Wallace <vwallace@protonmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning = { version = "0.0.108", features = ["max_level_trace"] }
lightning-block-sync = { version = "0.0.108", features = [ "rpc-client" ] }
lightning-invoice = { version = "0.16" }
lightning-net-tokio = { version = "0.0.108" }
lightning-persister = { version = "0.0.108" }
lightning-background-processor = { version = "0.0.108" }
lightning-rapid-gossip-sync = { version = "0.0.108" }

base64 = "0.13.0"
bitcoin = "0.28.1"
bitcoin-bech32 = "0.12"
bech32 = "0.8"
hex = "0.3"
reqwest = "0.11.11"
futures = "0.3"
chrono = "0.4"
rand = "0.4"
serde_json = { version = "1.0" }
tokio = { version = "1", features = [ "io-util", "macros", "rt", "rt-multi-thread", "sync", "net", "time" ] }
tor = { git = "https://github.com/Sifir-io/sifir-rs-sdk" }
tor-stream = "0.3.0"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
